# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
